### ISSUE TITLE
Api key not found ?

### ISSUE THREAD

**Issue by gumruk1905** [DarkMakerofc/OpenAi-ChatGPT-Bot#2]
Where do I write the api key?

**Comment by DarkMakerofc** [comment]
1. Login Open Ai site
2. get api key
3. put your api key
    .setapi < your api key > 
<b> Example </b>
![IMG-20230623-WA0008](https://github.com/DarkMakerofc/OpenAi-ChatGPT-Bot/assets/108072422/8bd4d22a-b0ee-4237-a1cd-214b19b84edb)

**Comment by joaog97** [comment]
> 1. Login Open Ai site
> 2. get api key
> 3. put your api key
>    .setapi < your api key >
>     Example 
>    ![IMG-20230623-WA0008](https://user-images.githubusercontent.com/108072422/248151157-8bd4d22a-b0ee-4237-a1cd-214b19b84edb.jpg)

where do i write the api key?

**Comment by Samridhya01** [comment]
Not work

**Comment by Pannelious** [comment]
Hello i cant have api key because im in country that openai doesn't support help pliz
